//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.BizTalk.Pipelines.CustomComponent.PropertyGeneratorPipeline {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertyGeneratorRespurceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyGeneratorRespurceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.BizTalk.Pipelines.CustomComponent.PropertyGeneratorPipeline.PropertyGen" +
                            "eratorRespurceFile", typeof(PropertyGeneratorRespurceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string customPromotedPropertyNameProp {
            get {
                return ResourceManager.GetString("customPromotedPropertyNameProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string customPromotedPropertyNameSpaceProp {
            get {
                return ResourceManager.GetString("customPromotedPropertyNameSpaceProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom namespace.
        /// </summary>
        internal static string customPromotedPropertyNameSpaceText {
            get {
                return ResourceManager.GetString("customPromotedPropertyNameSpaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the property to promote.
        /// </summary>
        internal static string customPromotedPropertyNameText {
            get {
                return ResourceManager.GetString("customPromotedPropertyNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string customPromotedPropertyValueProp {
            get {
                return ResourceManager.GetString("customPromotedPropertyValueProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of the promoted Property.
        /// </summary>
        internal static string customPromotedPropertyValueText {
            get {
                return ResourceManager.GetString("customPromotedPropertyValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PipelineTool {
            get {
                object obj = ResourceManager.GetObject("PipelineTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
