echo on
copy "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\MessageInstances\nonVIPIncomingBookOrders_output.xml" "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\Ports\IN"
timeout /t 2
copy "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\MessageInstances\nonVIPIncomingBookOrders_output.xml" "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\Ports\IN"
timeout /t 2
copy "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\MessageInstances\nonVIPIncomingBookOrders_output.xml" "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\Ports\IN"
timeout /t 2
copy "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\MessageInstances\nonVIPIncomingBookOrders_output.xml" "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\Ports\IN"
timeout /t 2
copy "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\MessageInstances\nonVIPIncomingBookOrders_output.xml" "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\Ports\IN"
timeout /t 2
copy "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\MessageInstances\nonVIPIncomingBookOrders_output.xml" "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\Ports\IN"
timeout /t 2
copy "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\MessageInstances\nonVIPIncomingBookOrders_output.xml" "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\Ports\IN"
timeout /t 2
copy "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\MessageInstances\nonVIPIncomingBookOrders_output.xml" "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\Ports\IN"
timeout /t 2
copy "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\MessageInstances\nonVIPIncomingBookOrders_output.xml" "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\Ports\IN"
timeout /t 2
copy "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\MessageInstances\nonVIPIncomingBookOrders_output.xml" "C:\APRESS\Chapter5\BookOrdersSolutionBase\BookOrdersSolution\Ports\IN"
timeout /t 2